import type { ExecutionsQualityData } from "./types";

// Phase 10: full mirror of the JSON contract in docs/06-execucoes-e-qualidade.md.
// Replace with the real API output (api.listRuns, api.getOverview, api.getDataQuality)
// once endpoints are wired.
export const executionsQualityMock: ExecutionsQualityData = {
  screen: {
    id: "executions-quality",
    title: "Execuções & Qualidade",
    subtitle: "Gerencie execuções do modelo e garanta confiança nas análises.",
    route: "/execucoes-e-qualidade",
    activeNav: "Execuções & Qualidade",
  },
  topBar: {
    actions: [
      { id: "newExecution", label: "Nova execução", icon: "Plus", variant: "primary" },
      {
        id: "modelParameters",
        label: "Parâmetros do modelo",
        icon: "Settings",
        variant: "secondary",
      },
      { id: "export", label: "Exportar", icon: "Download", variant: "secondary" },
    ],
  },
  summaryMetrics: [
    {
      id: "totalExecutions",
      title: "Total de execuções",
      value: "87",
      icon: "SlidersHorizontal",
      tone: "blue",
      delta: { value: "+14", label: "vs. mês anterior", tone: "positive" },
    },
    {
      id: "lastConfidence",
      title: "Confiança da última execução",
      value: "92%",
      badge: "Alta",
      icon: "ShieldCheck",
      tone: "green",
      delta: { value: "+6 p.p.", label: "vs. execução anterior", tone: "positive" },
    },
    {
      id: "averageRuntime",
      title: "Runtime médio",
      value: "2,6 h",
      icon: "Clock",
      tone: "blue",
      delta: { value: "-0,4 h", label: "vs. mês anterior", tone: "positive" },
    },
    {
      id: "criticalAlerts",
      title: "Alertas críticos",
      value: "2",
      icon: "TriangleAlert",
      tone: "red",
      subtitle: "Atenção necessária",
    },
  ],
  executionHistory: {
    title: "Histórico de execuções",
    controls: [
      { id: "search", placeholder: "Buscar execução..." },
      { id: "filter", label: "Filtrar", icon: "ListFilter" },
    ],
    columns: [
      "Período",
      "Status",
      "Receita",
      "Conversão observada",
      "Conversão modelada",
      "Confiança",
      "Runtime",
      "Criado por",
      "Ações",
    ],
    rows: [
      {
        id: "01 Abr — 30 Abr 2026",
        period: "01 Abr — 30 Abr 2026",
        status: "Concluído",
        statusTone: "green",
        revenue: "R$ 24,8M",
        observedConversion: "3,09%",
        modeledConversion: "3,48%",
        confidence: "92%",
        confidenceBadge: "Alta",
        runtime: "2h 18m",
        createdBy: "Ana Martins",
        createdAt: "30 Abr 2026, 08:24",
        selected: true,
      },
      {
        id: "01 Mar — 31 Mar 2026",
        period: "01 Mar — 31 Mar 2026",
        status: "Em processamento",
        statusTone: "blue",
        revenue: "R$ 22,1M",
        observedConversion: "2,98%",
        modeledConversion: "3,31%",
        confidence: "—",
        runtime: "1h 07m (76%)",
        createdBy: "Ana Martins",
        createdAt: "Hoje, 09:11",
      },
      {
        id: "01 Fev — 28 Fev 2026",
        period: "01 Fev — 28 Fev 2026",
        status: "Atenção",
        statusTone: "orange",
        revenue: "R$ 20,5M",
        observedConversion: "2,71%",
        modeledConversion: "3,12%",
        confidence: "68%",
        confidenceBadge: "Média",
        runtime: "2h 41m",
        createdBy: "Ana Martins",
        createdAt: "01 Mar 2026, 08:16",
      },
      {
        id: "01 Jan — 31 Jan 2026",
        period: "01 Jan — 31 Jan 2026",
        status: "Concluído",
        statusTone: "green",
        revenue: "R$ 18,7M",
        observedConversion: "2,63%",
        modeledConversion: "3,05%",
        confidence: "88%",
        confidenceBadge: "Alta",
        runtime: "2h 07m",
        createdBy: "Rodrigo Silva",
        createdAt: "01 Fev 2026, 09:02",
      },
      {
        id: "01 Dez 2025 — 31 Dez 2025",
        period: "01 Dez 2025 — 31 Dez 2025",
        status: "Concluído",
        statusTone: "green",
        revenue: "R$ 17,2M",
        observedConversion: "2,50%",
        modeledConversion: "2,94%",
        confidence: "85%",
        confidenceBadge: "Alta",
        runtime: "1h 59m",
        createdBy: "Rodrigo Silva",
        createdAt: "01 Jan 2026, 08:45",
      },
    ],
    pagination: {
      summary: "Mostrando 1 a 5 de 87 execuções",
      pages: [1, 2, 3, "...", 18],
    },
  },
  trustCenter: {
    title: "Trust Center",
    overallConfidence: {
      value: "92%",
      badge: "Alta",
      delta: "+6 p.p. vs. execução anterior",
    },
    modelCalibration: [
      { label: "Conversão modelada vs. observada", value: "94%" },
      { label: "Receita modelada vs. observada", value: "91%" },
    ],
    dataQuality: [
      { label: "Qualidade dos dados", value: "96%" },
      { label: "Cobertura de eventos", value: "98%" },
      { label: "Match de usuários", value: "93%" },
      { label: "Direct share (baseada em brand lift)", value: "12%" },
      { label: "Other share (orgânico + direto não atribuído)", value: "14%" },
      { label: "Cobertura de investimento", value: "97%" },
    ],
    alerts: {
      title: "Alertas críticos (2)",
      items: [
        "Cobertura de investimento abaixo do ideal. 7% do investimento não foi coberto pelos dados.",
        "Queda na calibração de receita. Diferença de 9 p.p. vs. execução anterior.",
      ],
      action: "Ver todos os alertas",
    },
    checks: {
      title: "Checks de qualidade",
      value: "8/8",
      description: "Todos os checks passaram",
      action: "Ver detalhes dos checks",
    },
  },
  compareExecutions: {
    title: "Comparar execuções",
    from: "01 Abr — 30 Abr 2026 (Atual)",
    to: "01 Mar — 31 Mar 2026 (Anterior)",
    variation: {
      title: "Variação de receita total",
      value: "+ R$ 2,7M",
      delta: "+12,2%",
    },
    channelContributionChange: [
      {
        channel: "Google Ads",
        from: "1,27%",
        to: "1,36%",
        delta: "+0,09 p.p.",
        tone: "positive",
      },
      {
        channel: "Meta Ads",
        from: "0,92%",
        to: "0,85%",
        delta: "-0,07 p.p.",
        tone: "negative",
      },
      {
        channel: "WhatsApp CRM",
        from: "0,38%",
        to: "0,45%",
        delta: "+0,07 p.p.",
        tone: "positive",
      },
      {
        channel: "Email",
        from: "0,23%",
        to: "0,21%",
        delta: "-0,02 p.p.",
        tone: "negative",
      },
      {
        channel: "Display",
        from: "0,17%",
        to: "0,16%",
        delta: "-0,01 p.p.",
        tone: "negative",
      },
      {
        channel: "Outros",
        from: "0,51%",
        to: "0,45%",
        delta: "-0,06 p.p.",
        tone: "negative",
      },
    ],
    legend: [
      { label: "Aumentou", tone: "green" },
      { label: "Diminuiu", tone: "red" },
      { label: "Estável", tone: "neutral" },
    ],
    action: "Ver comparação completa",
  },
  executionDetailsPanel: {
    title: "Detalhes da execução",
    period: "01 Abr — 30 Abr 2026",
    status: "Concluído",
    createdAt: "30 Abr 2026, 08:24",
    createdBy: "Ana Martins",
    tabs: ["Parâmetros", "Entradas", "Saídas", "Logs"],
    activeTab: "Parâmetros",
    modelParameters: [
      { label: "Lookback (janela de análise)", value: "90 dias" },
      { label: "Decaimento (lambda - half-life)", value: "30 dias" },
      { label: "Amostras Shapley", value: "100.000" },
      { label: "Amostra não-conversão", value: "1.000.000" },
      { label: "Janela de censura", value: "7 dias" },
      { label: "Granularidade", value: "Diária" },
      { label: "Moeda", value: "BRL" },
      { label: "Modelo de atribuição", value: "Shapley Value" },
      { label: "Versão do algoritmo", value: "v2026.05.31.01" },
    ],
    notes: {
      title: "Notas",
      value: "Execução mensal padrão.",
      action: "Editar",
    },
    confidenceBox: {
      title: "Confiança desta execução: Alta",
      description:
        "Modelo alinhado com os dados de alta qualidade. Recomendações com alto grau de confiança.",
      action: "Ver detalhes técnicos",
    },
    actions: [
      { id: "rerun", label: "Reexecutar", icon: "RefreshCw", variant: "secondary" },
      { id: "more", label: "Mais", icon: "Ellipsis", variant: "icon" },
    ],
  },
} as const;
