"""Pydantic row schemas — one class per endpoint table row.

These are the single source of truth for the shape of `TableResponse.rows`
returned by `/model-runs/{id}/<table>` endpoints. Each schema mirrors the
fields produced by the corresponding service (or persisted in `db/models.py`).

All fields default to `None` so coercion from heterogeneous pandas DataFrames
(where columns may be missing or NaN) is forgiving. Endpoints normalize NaN
to `None` before validation.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


_ROW_CONFIG = ConfigDict(from_attributes=True, populate_by_name=True)


class ChannelMetricRow(BaseModel):
    """Row for `/channels` and `/raw-channels` (attribution_results + ROAS merge)."""

    model_config = _ROW_CONFIG

    channel: str
    model_type: Optional[str] = None
    markov_weight: Optional[float] = None
    markov_revenue: Optional[float] = None
    removal_effect: Optional[float] = None
    shapley_weight: Optional[float] = None
    shapley_revenue: Optional[float] = None
    shapley_value: Optional[float] = None
    spend: Optional[float] = None
    roas_markov: Optional[float] = None
    roas_shapley: Optional[float] = None
    first_click_revenue: Optional[float] = None
    first_click_roas: Optional[float] = None
    last_click_revenue: Optional[float] = None
    last_click_roas: Optional[float] = None
    pfc_weight: Optional[float] = None
    pfc_delta_pp: Optional[float] = None
    recommendation: Optional[str] = None
    confidence_score: Optional[float] = None


class DiagnosticRow(BaseModel):
    """Row for `/diagnostics` (channel_diagnostics)."""

    model_config = _ROW_CONFIG

    channel: str
    channel_role: Optional[str] = None
    touchpoint_role: Optional[str] = None
    presence_converting: Optional[float] = None
    presence_nonconverting: Optional[float] = None
    first_touch_share: Optional[float] = None
    middle_touch_share: Optional[float] = None
    last_touch_share: Optional[float] = None
    assist_count: Optional[float] = None
    closer_count: Optional[float] = None
    starter_count: Optional[float] = None
    markov_shapley_delta_pp: Optional[float] = None
    diagnostic_label: Optional[str] = None
    diagnostic_text: Optional[str] = None


class InsightRow(BaseModel):
    """Row for `/insights` — generated by journey_insight_service."""

    model_config = _ROW_CONFIG

    channel: str
    title: Optional[str] = None
    description: Optional[str] = None
    evidence: Optional[str] = None
    metric: Optional[str] = None
    severity: Optional[str] = None
    confidence: Optional[str] = None
    recommendation: Optional[str] = None
    limitation: Optional[str] = None


class TouchpointRow(BaseModel):
    """Row for `/touchpoints` — derived from transition_counts."""

    model_config = _ROW_CONFIG

    channel: str
    conv_first_touch_share: Optional[float] = None
    conv_middle_touch_share: Optional[float] = None
    conv_last_touch_share: Optional[float] = None
    nonconv_first_touch_share: Optional[float] = None
    nonconv_middle_touch_share: Optional[float] = None
    nonconv_last_touch_share: Optional[float] = None
    starter_count: Optional[float] = None
    assist_count: Optional[float] = None
    closer_count: Optional[float] = None
    dropoff_after_touch: Optional[float] = None
    touchpoint_role: Optional[str] = None


class TransitionRow(BaseModel):
    """Row for `/transitions` (transition_counts)."""

    model_config = _ROW_CONFIG

    from_state: str
    to_state: str
    n: Optional[float] = None
    total_revenue: Optional[float] = None
    transition_type: Optional[str] = None


class PathRow(BaseModel):
    """Row for `/paths` and `/loops` (path_summary)."""

    model_config = _ROW_CONFIG

    path_hash: Optional[str] = None
    path_text: str
    path_length: Optional[int] = None
    count: Optional[float] = None
    conversion_count: Optional[float] = None
    nonconversion_count: Optional[float] = None
    conversion_rate: Optional[float] = None
    revenue: Optional[float] = None
    avg_ticket: Optional[float] = None
    path_probability: Optional[float] = None
    contains_loop: Optional[int] = None
    confidence_score: Optional[float] = None


class DataQualityRow(BaseModel):
    """Row for `/data-quality` (data_quality_checks)."""

    model_config = _ROW_CONFIG

    check_name: str
    status: Optional[str] = None
    severity: Optional[str] = None
    detail: Optional[str] = None


class LoopDiagnosticRow(BaseModel):
    """Row for `/loop-diagnostics` (loop_diagnostics)."""

    model_config = _ROW_CONFIG

    channel: str
    self_loop_count: Optional[float] = None
    self_loop_rate: Optional[float] = None
    avg_consecutive_repeats: Optional[float] = None
    median_consecutive_repeats: Optional[float] = None
    max_consecutive_repeats: Optional[float] = None
    loop_conversion_rate: Optional[float] = None
    nonloop_conversion_rate: Optional[float] = None
    loop_conversion_lift: Optional[float] = None
    exit_distribution_json: Optional[str] = None
    support: Optional[int] = None
    confidence: Optional[str] = None


class FunnelAttributionRow(BaseModel):
    """Row for `/funnel-attribution` (funnel_state_attribution)."""

    model_config = _ROW_CONFIG

    state: str
    channel: str
    funnel_stage: Optional[str] = None
    markov_weight: Optional[float] = None
    markov_revenue: Optional[float] = None
    removal_effect: Optional[float] = None
    shapley_weight: Optional[float] = None
    shapley_revenue: Optional[float] = None
    presence_converting: Optional[float] = None
    presence_nonconverting: Optional[float] = None
    support: Optional[int] = None
    confidence: Optional[str] = None


class FunnelValidationRow(BaseModel):
    """Row for `/funnel-validation` — aggregated per channel from funnel_state_attribution."""

    model_config = _ROW_CONFIG

    channel: str
    funnel_markov_weight: Optional[float] = None
    raw_markov_weight: Optional[float] = None
    low_intent_weight: Optional[float] = None
    product_interest_weight: Optional[float] = None
    cart_intent_weight: Optional[float] = None
    checkout_weight: Optional[float] = None
    purchase_weight: Optional[float] = None
    qualified_weight: Optional[float] = None
    low_intent_drag_score: Optional[float] = None
    qualified_intent_share: Optional[float] = None
    markov_excl_low_intent: Optional[float] = None


class SequentialEffectRow(BaseModel):
    """Row for `/sequential-effects` (sequential_effects)."""

    model_config = _ROW_CONFIG

    previous_channel: str
    current_channel: str
    pair_count: Optional[float] = None
    conversion_count: Optional[float] = None
    nonconversion_count: Optional[float] = None
    conversion_probability_pair: Optional[float] = None
    conversion_probability_baseline: Optional[float] = None
    lift_vs_baseline: Optional[float] = None
    avg_ticket: Optional[float] = None
    revenue: Optional[float] = None
    support: Optional[int] = None
    confidence: Optional[str] = None
    diagnostic_label: Optional[str] = None


class SessionQualityRow(BaseModel):
    """Row for `/session-quality` (session_quality) — full SessionQuality shape."""

    model_config = _ROW_CONFIG

    channel: str
    sessions: Optional[int] = None
    avg_duration_s: Optional[float] = None
    avg_pageviews: Optional[float] = None
    avg_bounce_rate: Optional[float] = None
    avg_events: Optional[float] = None
    conv_sessions: Optional[int] = None
    conv_avg_duration_s: Optional[float] = None
    conv_avg_bounce_rate: Optional[float] = None
    nonconv_avg_duration_s: Optional[float] = None
    nonconv_avg_bounce_rate: Optional[float] = None
