import type { LiftEngineData } from "./types";

export const liftEngineMock: LiftEngineData = {
  screen: {
    title: "Motor de Lift",
    subtitle: "Oportunidades de crescimento identificadas por análise de jornada",
  },
  metrics: {
    totalInsights: 10,
    avgLift: 112,
    criticalCount: 3,
    estimatedRevImpact: "R$ 2.4M",
  },
  insights: [
    {
      id: "youtube-canal",
      title: "YouTube aparece em jornadas 59% mais propensas à conversão",
      category: "canal",
      liftPct: 59,
      confidence: "alta",
      priority: "critica",
      baseLabel: "Facebook → Produto → Compra",
      liftLabel: "Facebook → YouTube → Produto → Compra",
      baseConvRate: 0.032,
      liftConvRate: 0.051,
      evidence: [
        "18% dos usuários convertidos passaram por YouTube na jornada",
        "Apenas 7% dos não-convertidos tiveram exposição a YouTube",
        "O tempo médio até a compra cai 1,8 dias quando YouTube está presente",
      ],
      hypothesis:
        "YouTube aumenta familiaridade com a marca antes da visita ao site, reduzindo a fricção na decisão de compra.",
      actions: [
        "Expandir investimento em YouTube com criativos educativos",
        "Criar sequência de remarketing para usuários impactados por YouTube",
        "Testar YouTube como pré-qualificador antes de campanhas de conversão no Meta",
      ],
    },
    {
      id: "avaliacoes-conteudo",
      title: "Usuários que interagem com avaliações convertem 90% mais",
      category: "conteudo",
      liftPct: 90,
      confidence: "alta",
      priority: "critica",
      baseLabel: "Facebook → Produto → Compra",
      liftLabel: "Facebook → Produto → Avaliações → Compra",
      baseConvRate: 0.02,
      liftConvRate: 0.038,
      evidence: [
        "38,2% dos pedidos vêm de sessões com interação em avaliações",
        "Sessões sem interação com avaliações apresentam bounce 2,3× maior na PDP",
        "Produtos com ≥ 50 avaliações têm ticket médio 12% maior",
      ],
      hypothesis:
        "Avaliações atuam como prova social que reduz a incerteza na compra, especialmente para novos usuários vindos de Meta.",
      actions: [
        "Garantir visibilidade das avaliações acima do botão de compra na PDP",
        "Criar UGC ads destacando avaliações reais",
        "Implementar notificação proativa de avaliações para usuários indecisos no carrinho",
      ],
    },
    {
      id: "influenciadores-canal",
      title: "Influenciadores no path elevam conversão em 84%",
      category: "canal",
      liftPct: 84,
      confidence: "alta",
      priority: "critica",
      baseLabel: "Facebook → Produto → Compra",
      liftLabel: "Influenciador → Facebook → Produto → Compra",
      baseConvRate: 0.025,
      liftConvRate: 0.046,
      evidence: [
        "Jornadas com touchpoint de influenciador têm ticket médio 18% acima da média",
        "Usuários vindos via UTM de influenciadores retornam em 2,1 sessões antes de comprar",
        "Taxa de recompra desse segmento é 34% maior que a média geral",
      ],
      hypothesis:
        "Influenciadores geram demanda qualificada com forte prova social, criando um pré-aquecimento eficaz antes da exposição a anúncios diretos.",
      actions: [
        "Priorizar influenciadores cujas UTMs mostram maior overlap com campanhas Meta de conversão",
        "Criar audiências lookalike a partir de usuários com UTM de influenciador",
        "Testar criativos UGC de influenciadores nas campanhas de remarketing",
      ],
    },
    {
      id: "add-to-cart-evento",
      title: "Add to Cart é o evento com maior poder preditivo de compra",
      category: "evento",
      liftPct: 312,
      confidence: "alta",
      priority: "alta",
      evidence: [
        "Usuários com ATC convertem a 14,8% vs 3,6% sem ATC na mesma sessão",
        "68% das compras são precedidas por ATC na mesma sessão",
        "Usuários com ATC sem compra que retornam em até 24h convertem a 31%",
      ],
      hypothesis:
        "O evento de ATC é o sinal mais forte de intenção de compra; o gap entre ATC e compra representa a maior oportunidade de recuperação.",
      actions: [
        "Ativar remarketing agressivo para usuários com ATC sem compra nas primeiras 6h",
        "Implementar email/WhatsApp de abandono de carrinho com incentivo",
        "Reduzir atrito no checkout para usuários mobile (maior taxa de abandono pós-ATC)",
      ],
    },
    {
      id: "categoria-pagina",
      title: "Explorar categorias antes do produto aumenta a intenção de compra",
      category: "pagina",
      liftPct: 47,
      confidence: "media",
      priority: "alta",
      baseLabel: "Facebook → Produto → Compra",
      liftLabel: "Facebook → Categoria → Produto → Compra",
      baseConvRate: 0.028,
      liftConvRate: 0.041,
      evidence: [
        "Jornadas com visita a página de categoria antes da PDP convertem 47% mais",
        "Sessões com 2+ páginas de categoria têm tempo médio 3,2× maior",
        "Usuários que exploram categorias visitam 2,8 PDPs vs 1,1 dos usuários diretos",
      ],
      hypothesis:
        "Navegar por categorias indica usuário em modo de descoberta com maior intenção de compra — o site deve facilitar essa exploração.",
      actions: [
        "Melhorar CTAs de categoria nas campanhas de awareness do Meta",
        "Criar páginas de coleção temáticas para capturar tráfego de descoberta",
        "Otimizar navegação interna entre categorias relacionadas",
      ],
    },
    {
      id: "google-sequencia",
      title: "Google Search como último touchpoint antes de Meta aumenta conversão",
      category: "sequencia",
      liftPct: 67,
      confidence: "media",
      priority: "alta",
      baseLabel: "Meta → Produto → Compra",
      liftLabel: "Meta → Google Search → Produto → Compra",
      baseConvRate: 0.03,
      liftConvRate: 0.05,
      evidence: [
        "Jornadas com Search após exposição Meta convertem 67% acima da média",
        "Indica usuário que validou interesse pesquisando a marca explicitamente",
        "ROAS combinado Meta+Search é 2,4× maior que Meta isolado",
      ],
      hypothesis:
        "Meta gera awareness, Google Search captura a intenção validada — a sequência Meta→Search→Compra representa o funil mais eficiente.",
      actions: [
        "Aumentar budget de Search branded para capturar demanda gerada pelo Meta",
        "Criar campanhas SKAG para termos de produto específicos impulsionados por Meta",
        "Mapear termos de busca pós-exposição Meta para alimentar creative do Meta",
      ],
    },
    {
      id: "scroll-depth-evento",
      title: "Scroll depth > 75% na PDP prediz compra com lift de 178%",
      category: "evento",
      liftPct: 178,
      confidence: "media",
      priority: "media",
      evidence: [
        "Usuários com scroll > 75% na PDP convertem a 9,4% vs 3,4% média",
        "Correlaciona com visualização de avaliações e FAQ da página",
        "Presença desse evento em 73% das jornadas convertidas vs 29% das não-convertidas",
      ],
      hypothesis:
        "Scroll profundo indica que o usuário consumiu toda a proposta de valor da página — conteúdo abaixo da dobra tem impacto relevante na decisão.",
      actions: [
        "Garantir que benefícios, avaliações e garantias apareçam no primeiro scroll",
        "Testar A/B com CTA flutuante que apareça ao atingir 75% de scroll",
        "Analisar quais elementos abaixo da dobra correlacionam mais com a compra",
      ],
    },
    {
      id: "display-remarketing-canal",
      title: "Display/Criteo em jornadas assistidas eleva fechamento em 41%",
      category: "canal",
      liftPct: 41,
      confidence: "media",
      priority: "media",
      baseLabel: "Meta → Produto → (saída)",
      liftLabel: "Meta → Produto → Display → Compra",
      baseConvRate: 0.022,
      liftConvRate: 0.031,
      evidence: [
        "41% de lift em conversão quando Display aparece como canal assistido",
        "Investimento <R$ 2k/dia com participação relevante em jornadas de 3+ touchpoints",
        "ROI assistido do Display é 3,8× maior que o atribuído diretamente",
      ],
      hypothesis:
        "Display atua como lembrete de reconsideração para usuários que saíram sem comprar — seu impacto assistido é sistematicamente subestimado.",
      actions: [
        "Avaliar aumento de budget em Display considerando contribuição assistida",
        "Criar segmentos específicos de remarketing por produto visualizado",
        "Testar criativos dinâmicos com produtos visualizados nas sessões anteriores",
      ],
    },
    {
      id: "ugc-conteudo",
      title: "Interação com UGC/conteúdo de influenciador dentro do site gera +145% de lift",
      category: "conteudo",
      liftPct: 145,
      confidence: "baixa",
      priority: "alta",
      evidence: [
        "Páginas com galeria UGC têm taxa de conversão 2,4× maior",
        "Usuários que clicam em vídeos de influenciador na PDP têm ATC 3× mais frequente",
        "Baixo volume de dados — amostra ainda limitada para alta confiança",
      ],
      hypothesis:
        "UGC dentro do site replica o efeito social do influenciador no momento de decisão de compra, reduzindo a incerteza no ponto mais crítico.",
      actions: [
        "Expandir galeria UGC para todas as PDPs de produtos top 20 em receita",
        "Testar vídeos de influenciadores embedados na PDP acima da dobra",
        "Instrumentar eventos de clique em UGC para aumentar confiança estatística",
      ],
    },
    {
      id: "tiktok-sequencia",
      title: "TikTok como canal de entrada precede jornadas com maior ticket médio",
      category: "sequencia",
      liftPct: 33,
      confidence: "baixa",
      priority: "media",
      baseLabel: "Meta → Produto → Compra",
      liftLabel: "TikTok → Meta → Produto → Compra",
      baseConvRate: 0.019,
      liftConvRate: 0.025,
      evidence: [
        "Jornadas iniciadas no TikTok têm ticket médio R$ 47 acima da média geral",
        "Volume ainda reduzido — TikTok representa <5% das jornadas mapeadas",
        "Sinal positivo de que o público TikTok tem perfil demográfico distinto e complementar",
      ],
      hypothesis:
        "TikTok atinge um segmento mais jovem com alta intenção de descoberta — quando ativados pelo Meta após exposição TikTok, convertem com ticket superior.",
      actions: [
        "Aumentar investimento em TikTok para gerar massa de dados suficiente para validar",
        "Criar criativos TikTok-native com foco em descoberta de produto",
        "Mapear overlap de audiências TikTok e Meta para segmentação cruzada",
      ],
    },
  ],
};
